	mnDualHostifGpio u0 (
		.memory_mem_a                                      (<connected-to-memory_mem_a>),                                      //                         memory.mem_a
		.memory_mem_ba                                     (<connected-to-memory_mem_ba>),                                     //                               .mem_ba
		.memory_mem_ck                                     (<connected-to-memory_mem_ck>),                                     //                               .mem_ck
		.memory_mem_ck_n                                   (<connected-to-memory_mem_ck_n>),                                   //                               .mem_ck_n
		.memory_mem_cke                                    (<connected-to-memory_mem_cke>),                                    //                               .mem_cke
		.memory_mem_cs_n                                   (<connected-to-memory_mem_cs_n>),                                   //                               .mem_cs_n
		.memory_mem_ras_n                                  (<connected-to-memory_mem_ras_n>),                                  //                               .mem_ras_n
		.memory_mem_cas_n                                  (<connected-to-memory_mem_cas_n>),                                  //                               .mem_cas_n
		.memory_mem_we_n                                   (<connected-to-memory_mem_we_n>),                                   //                               .mem_we_n
		.memory_mem_reset_n                                (<connected-to-memory_mem_reset_n>),                                //                               .mem_reset_n
		.memory_mem_dq                                     (<connected-to-memory_mem_dq>),                                     //                               .mem_dq
		.memory_mem_dqs                                    (<connected-to-memory_mem_dqs>),                                    //                               .mem_dqs
		.memory_mem_dqs_n                                  (<connected-to-memory_mem_dqs_n>),                                  //                               .mem_dqs_n
		.memory_mem_odt                                    (<connected-to-memory_mem_odt>),                                    //                               .mem_odt
		.memory_mem_dm                                     (<connected-to-memory_mem_dm>),                                     //                               .mem_dm
		.memory_oct_rzqin                                  (<connected-to-memory_oct_rzqin>),                                  //                               .oct_rzqin
		.memory_0_mem_a                                    (<connected-to-memory_0_mem_a>),                                    //                       memory_0.mem_a
		.memory_0_mem_ba                                   (<connected-to-memory_0_mem_ba>),                                   //                               .mem_ba
		.memory_0_mem_ck                                   (<connected-to-memory_0_mem_ck>),                                   //                               .mem_ck
		.memory_0_mem_ck_n                                 (<connected-to-memory_0_mem_ck_n>),                                 //                               .mem_ck_n
		.memory_0_mem_cke                                  (<connected-to-memory_0_mem_cke>),                                  //                               .mem_cke
		.memory_0_mem_cs_n                                 (<connected-to-memory_0_mem_cs_n>),                                 //                               .mem_cs_n
		.memory_0_mem_dm                                   (<connected-to-memory_0_mem_dm>),                                   //                               .mem_dm
		.memory_0_mem_ras_n                                (<connected-to-memory_0_mem_ras_n>),                                //                               .mem_ras_n
		.memory_0_mem_cas_n                                (<connected-to-memory_0_mem_cas_n>),                                //                               .mem_cas_n
		.memory_0_mem_we_n                                 (<connected-to-memory_0_mem_we_n>),                                 //                               .mem_we_n
		.memory_0_mem_reset_n                              (<connected-to-memory_0_mem_reset_n>),                              //                               .mem_reset_n
		.memory_0_mem_dq                                   (<connected-to-memory_0_mem_dq>),                                   //                               .mem_dq
		.memory_0_mem_dqs                                  (<connected-to-memory_0_mem_dqs>),                                  //                               .mem_dqs
		.memory_0_mem_dqs_n                                (<connected-to-memory_0_mem_dqs_n>),                                //                               .mem_dqs_n
		.memory_0_mem_odt                                  (<connected-to-memory_0_mem_odt>),                                  //                               .mem_odt
		.oct_rzqin                                         (<connected-to-oct_rzqin>),                                         //                            oct.rzqin
		.clk_50_clk                                        (<connected-to-clk_50_clk>),                                        //                         clk_50.clk
		.reset_reset_n                                     (<connected-to-reset_reset_n>),                                     //                          reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),             //                   hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),               //                               .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),               //                               .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),               //                               .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),               //                               .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),               //                               .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),               //                               .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC                (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),                //                               .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),             //                               .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),             //                               .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),             //                               .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),               //                               .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),               //                               .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),               //                               .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_qspi_inst_IO0                 (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO0>),                 //                               .hps_io_qspi_inst_IO0
		.hps_0_hps_io_hps_io_qspi_inst_IO1                 (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO1>),                 //                               .hps_io_qspi_inst_IO1
		.hps_0_hps_io_hps_io_qspi_inst_IO2                 (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO2>),                 //                               .hps_io_qspi_inst_IO2
		.hps_0_hps_io_hps_io_qspi_inst_IO3                 (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO3>),                 //                               .hps_io_qspi_inst_IO3
		.hps_0_hps_io_hps_io_qspi_inst_SS0                 (<connected-to-hps_0_hps_io_hps_io_qspi_inst_SS0>),                 //                               .hps_io_qspi_inst_SS0
		.hps_0_hps_io_hps_io_qspi_inst_CLK                 (<connected-to-hps_0_hps_io_hps_io_qspi_inst_CLK>),                 //                               .hps_io_qspi_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_CMD                 (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),                 //                               .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),                  //                               .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),                  //                               .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK                 (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),                 //                               .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),                  //                               .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),                  //                               .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),                  //                               .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),                  //                               .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),                  //                               .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),                  //                               .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),                  //                               .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),                  //                               .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),                  //                               .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),                  //                               .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),                 //                               .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),                 //                               .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),                 //                               .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),                 //                               .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim0_inst_CLK                (<connected-to-hps_0_hps_io_hps_io_spim0_inst_CLK>),                //                               .hps_io_spim0_inst_CLK
		.hps_0_hps_io_hps_io_spim0_inst_MOSI               (<connected-to-hps_0_hps_io_hps_io_spim0_inst_MOSI>),               //                               .hps_io_spim0_inst_MOSI
		.hps_0_hps_io_hps_io_spim0_inst_MISO               (<connected-to-hps_0_hps_io_hps_io_spim0_inst_MISO>),               //                               .hps_io_spim0_inst_MISO
		.hps_0_hps_io_hps_io_spim0_inst_SS0                (<connected-to-hps_0_hps_io_hps_io_spim0_inst_SS0>),                //                               .hps_io_spim0_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX                 (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),                 //                               .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX                 (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),                 //                               .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA                 (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),                 //                               .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL                 (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),                 //                               .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_can0_inst_RX                  (<connected-to-hps_0_hps_io_hps_io_can0_inst_RX>),                  //                               .hps_io_can0_inst_RX
		.hps_0_hps_io_hps_io_can0_inst_TX                  (<connected-to-hps_0_hps_io_hps_io_can0_inst_TX>),                  //                               .hps_io_can0_inst_TX
		.hps_0_hps_io_hps_io_trace_inst_CLK                (<connected-to-hps_0_hps_io_hps_io_trace_inst_CLK>),                //                               .hps_io_trace_inst_CLK
		.hps_0_hps_io_hps_io_trace_inst_D0                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D0>),                 //                               .hps_io_trace_inst_D0
		.hps_0_hps_io_hps_io_trace_inst_D1                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D1>),                 //                               .hps_io_trace_inst_D1
		.hps_0_hps_io_hps_io_trace_inst_D2                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D2>),                 //                               .hps_io_trace_inst_D2
		.hps_0_hps_io_hps_io_trace_inst_D3                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D3>),                 //                               .hps_io_trace_inst_D3
		.hps_0_hps_io_hps_io_trace_inst_D4                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D4>),                 //                               .hps_io_trace_inst_D4
		.hps_0_hps_io_hps_io_trace_inst_D5                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D5>),                 //                               .hps_io_trace_inst_D5
		.hps_0_hps_io_hps_io_trace_inst_D6                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D6>),                 //                               .hps_io_trace_inst_D6
		.hps_0_hps_io_hps_io_trace_inst_D7                 (<connected-to-hps_0_hps_io_hps_io_trace_inst_D7>),                 //                               .hps_io_trace_inst_D7
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),              //                               .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),              //                               .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO41              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO41>),              //                               .hps_io_gpio_inst_GPIO41
		.hps_0_hps_io_hps_io_gpio_inst_GPIO42              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO42>),              //                               .hps_io_gpio_inst_GPIO42
		.hps_0_hps_io_hps_io_gpio_inst_GPIO43              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO43>),              //                               .hps_io_gpio_inst_GPIO43
		.hps_0_hps_io_hps_io_gpio_inst_GPIO44              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO44>),              //                               .hps_io_gpio_inst_GPIO44
		.led_pio_external_connection_in_port               (<connected-to-led_pio_external_connection_in_port>),               //    led_pio_external_connection.in_port
		.led_pio_external_connection_out_port              (<connected-to-led_pio_external_connection_out_port>),              //                               .out_port
		.dipsw_pio_external_connection_export              (<connected-to-dipsw_pio_external_connection_export>),              //  dipsw_pio_external_connection.export
		.button_pio_external_connection_export             (<connected-to-button_pio_external_connection_export>),             // button_pio_external_connection.export
		.hps_0_h2f_reset_reset_n                           (<connected-to-hps_0_h2f_reset_reset_n>),                           //                hps_0_h2f_reset.reset_n
		.hps_0_f2h_cold_reset_req_reset_n                  (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),                  //       hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n                 (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),                 //      hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_warm_reset_req_reset_n                  (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),                  //       hps_0_f2h_warm_reset_req.reset_n
		.ddr3_emif_0_status_local_init_done                (<connected-to-ddr3_emif_0_status_local_init_done>),                //             ddr3_emif_0_status.local_init_done
		.ddr3_emif_0_status_local_cal_success              (<connected-to-ddr3_emif_0_status_local_cal_success>),              //                               .local_cal_success
		.ddr3_emif_0_status_local_cal_fail                 (<connected-to-ddr3_emif_0_status_local_cal_fail>),                 //                               .local_cal_fail
		.ddr3_emif_0_pll_sharing_pll_mem_clk               (<connected-to-ddr3_emif_0_pll_sharing_pll_mem_clk>),               //        ddr3_emif_0_pll_sharing.pll_mem_clk
		.ddr3_emif_0_pll_sharing_pll_write_clk             (<connected-to-ddr3_emif_0_pll_sharing_pll_write_clk>),             //                               .pll_write_clk
		.ddr3_emif_0_pll_sharing_pll_locked                (<connected-to-ddr3_emif_0_pll_sharing_pll_locked>),                //                               .pll_locked
		.ddr3_emif_0_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-ddr3_emif_0_pll_sharing_pll_write_clk_pre_phy_clk>), //                               .pll_write_clk_pre_phy_clk
		.ddr3_emif_0_pll_sharing_pll_addr_cmd_clk          (<connected-to-ddr3_emif_0_pll_sharing_pll_addr_cmd_clk>),          //                               .pll_addr_cmd_clk
		.ddr3_emif_0_pll_sharing_pll_avl_clk               (<connected-to-ddr3_emif_0_pll_sharing_pll_avl_clk>),               //                               .pll_avl_clk
		.ddr3_emif_0_pll_sharing_pll_config_clk            (<connected-to-ddr3_emif_0_pll_sharing_pll_config_clk>),            //                               .pll_config_clk
		.ddr3_emif_0_pll_sharing_pll_dr_clk                (<connected-to-ddr3_emif_0_pll_sharing_pll_dr_clk>),                //                               .pll_dr_clk
		.ddr3_emif_0_pll_sharing_pll_dr_clk_pre_phy_clk    (<connected-to-ddr3_emif_0_pll_sharing_pll_dr_clk_pre_phy_clk>),    //                               .pll_dr_clk_pre_phy_clk
		.ddr3_emif_0_pll_sharing_pll_mem_phy_clk           (<connected-to-ddr3_emif_0_pll_sharing_pll_mem_phy_clk>),           //                               .pll_mem_phy_clk
		.ddr3_emif_0_pll_sharing_afi_phy_clk               (<connected-to-ddr3_emif_0_pll_sharing_afi_phy_clk>),               //                               .afi_phy_clk
		.ddr3_emif_0_pll_sharing_pll_avl_phy_clk           (<connected-to-ddr3_emif_0_pll_sharing_pll_avl_phy_clk>),           //                               .pll_avl_phy_clk
		.ddr3_emif_0_global_reset_reset_n                  (<connected-to-ddr3_emif_0_global_reset_reset_n>),                  //       ddr3_emif_0_global_reset.reset_n
		.ddr3_emif_0_afi_reset_export_reset_n              (<connected-to-ddr3_emif_0_afi_reset_export_reset_n>),              //   ddr3_emif_0_afi_reset_export.reset_n
		.ddr3_emif_0_soft_reset_reset_n                    (<connected-to-ddr3_emif_0_soft_reset_reset_n>),                    //         ddr3_emif_0_soft_reset.reset_n
		.clk_100_clk                                       (<connected-to-clk_100_clk>),                                       //                        clk_100.clk
		.openmac_0_mii_txEnable                            (<connected-to-openmac_0_mii_txEnable>),                            //                  openmac_0_mii.txEnable
		.openmac_0_mii_txData                              (<connected-to-openmac_0_mii_txData>),                              //                               .txData
		.openmac_0_mii_txClk                               (<connected-to-openmac_0_mii_txClk>),                               //                               .txClk
		.openmac_0_mii_rxError                             (<connected-to-openmac_0_mii_rxError>),                             //                               .rxError
		.openmac_0_mii_rxDataValid                         (<connected-to-openmac_0_mii_rxDataValid>),                         //                               .rxDataValid
		.openmac_0_mii_rxData                              (<connected-to-openmac_0_mii_rxData>),                              //                               .rxData
		.openmac_0_mii_rxClk                               (<connected-to-openmac_0_mii_rxClk>),                               //                               .rxClk
		.openmac_0_smi_nPhyRst                             (<connected-to-openmac_0_smi_nPhyRst>),                             //                  openmac_0_smi.nPhyRst
		.openmac_0_smi_clk                                 (<connected-to-openmac_0_smi_clk>),                                 //                               .clk
		.openmac_0_smi_dio                                 (<connected-to-openmac_0_smi_dio>),                                 //                               .dio
		.openmac_0_mactimerout_export                      (<connected-to-openmac_0_mactimerout_export>),                      //          openmac_0_mactimerout.export
		.ddr3_emif_0_pll_ref_clk_clk                       (<connected-to-ddr3_emif_0_pll_ref_clk_clk>),                       //        ddr3_emif_0_pll_ref_clk.clk
		.pcp_benchmark_pio_export                          (<connected-to-pcp_benchmark_pio_export>)                           //              pcp_benchmark_pio.export
	);

